packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  react: 19.3.0
  react-dom: 19.3.0
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
  tailwindcss: 4.3.3
  typescript: 7.0.2
  vite-plus: 1.0.0

minimumReleaseAgeExclude:
  - '@vue/compiler-core@3.5.43'
  - '@vue/compiler-dom@3.5.43'
  - '@vue/compiler-sfc@3.5.43'
  - '@vue/compiler-ssr@3.5.43'
  - '@vue/reactivity@3.5.43'
  - '@vue/runtime-core@3.5.43'
  - '@vue/runtime-dom@3.5.43'
  - '@vue/server-renderer@3.5.43'
  - '@vue/shared@3.5.43'
  - vue@3.5.43

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vitest: 4.1.11
